name: ci

on:
  push:
    branches:
      - mill-scala-native-verbose-linker-options
  workflow_dispatch: # be able to manually trigger a workflow run

env:
  JAVA: "21"
  VCPKG_FEATURE_FLAGS: dependencygraph
  VCPKG_DEFAULT_TRIPLET: "x64-windows-static"
  VCPKG_ROOT: "${{ github.workspace }}\\vcpkg"
  VCPKG_INSTALLED_DIR: "${{ github.workspace }}\\vcpkg\\installed"
  VCPKG_COMMIT_ID: "66c0373dc7fca549e5803087b9487edfe3aca0a1" # vcpkg 2026.01.16 Release

jobs:
  # test-libcurl-uninstalled:
  #   runs-on: "${{ matrix.platform }}"
  #   strategy:
  #     matrix:
  #       platform: [ubuntu-latest, windows-latest, macos-latest]
  #       verbose: [verbose, nonVerbose]
  #     fail-fast: false
  #   steps:
  #     - uses: actions/setup-java@v5
  #       with:
  #         java-version: "${{ env.JAVA }}"
  #         distribution: "temurin"
  #     - uses: actions/checkout@v6

  #     - name: Run main
  #       if: ${{ matrix.platform != 'windows-latest' }}
  #       run: |
  #         ./mill show ${{ matrix.verbose }}.nativeLinkingOptions
  #         ./mill ${{ matrix.verbose }}.run

  #     - name: Run main on Windows
  #       if: ${{ matrix.platform == 'windows-latest' }}
  #       env:
  #         SCALANATIVE_INCLUDE_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\include"
  #         SCALANATIVE_LIB_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\lib"
  #       run: |
  #         ./mill show ${{ matrix.verbose }}.nativeLinkingOptions
  #         ./mill ${{ matrix.verbose }}.run

  test-libcurl-installed:
    runs-on: "${{ matrix.platform }}"
    strategy:
      fail-fast: false
      matrix:
        platform:
          # - ubuntu-latest
          - windows-latest
          # - macos-latest
        verbose:
          - verbose
          # - nonVerbose
    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: "${{ env.JAVA }}"
          distribution: "temurin"
      - uses: actions/checkout@v6

      ## difference from test-libcurl-uninstalled: install libcurl via vcpkg or apt-get

      - name: Install Dependencies - Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: "${{ env.VCPKG_COMMIT_ID }}"
          runVcpkgInstall: true
          doNotCache: false

      - name: Install Dependencies - Linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Dependencies - macOS
        if: ${{ matrix.platform == 'macos-latest' }}
        run: |
          brew install curl openssl@3

      ## end of difference

      - name: Run main
        if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          ./mill show ${{ matrix.verbose }}.nativeLinkingOptions
          ./mill ${{ matrix.verbose }}.run

      - name: Run main on Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        env:
          SCALANATIVE_INCLUDE_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\include"
          SCALANATIVE_LIB_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\lib"
        run: |
          ./mill show ${{ matrix.verbose }}.nativeLinkingOptions
          ./mill ${{ matrix.verbose }}.run
